KBDEV-1236
bcgsc/pori_python pull request #25
Opened 2024-08-12 22:30 UTC by mathieulemieux

Added extra type checking for variant matching

2024-08-20 23:06 UTC, dustinbleile approved these changes, later dismissed

2024-09-24 16:39 UTC, dustinbleile submitted a review, later dismissed

2024-09-24 17:48 UTC, elewis2 approved these changes

2024-09-24 17:52 UTC, elewis2 requested changes

2024-09-24 17:52 UTC, elewis2 commented on pori_python/graphkb/match.py
> +        string: Wether or not only the specific-to-generic ones are considered.
var name not matching here and conn needs to be added

2024-09-25 17:48 UTC, dustinbleile commented on pori_python/graphkb/match.py
> +        strict: wether or not only the specific-to-generic ones are considered.
whether

2024-09-25 17:48 UTC, dustinbleile approved these changes

2024-09-25 17:49 UTC, dustinbleile approved these changes

2024-09-26 23:24 UTC, elewis2 approved these changes

2024-10-01 16:06 UTC, merged